version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/Bonpay Finance-frontend
      - /Bonpay Finance-frontend/node_modules
    environment:
      NODE_ENV: production
